services:
  client:
    image: ghcr.io/p0lloc/perfice:latest
    build:
      context: https://github.com/p0lloc/perfice.git#main:client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    restart: unless-stopped
