services:
  perfice:
    image: ghcr.io/p0lloc/perfice:latest   
    build:
      context: https://github.com/p0lloc/perfice.git
      dockerfile: client/Dockerfile
    container_name: perfice
    ports:
      - "6574:80"     
    restart: unless-stopped